//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShowPhones.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phone
    {
        public int id { get; set; }
        public string model { get; set; }
        public Nullable<decimal> price { get; set; }
        public string gerenal_not { get; set; }
    }
}
